name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    env:
      CARGO_INCREMENTAL: 0

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --all-features --verbose -- --include-ignored
      - name: Publish crate
        run: |
          cargo login ${{ secrets.CARGO_LOGIN_TOKEN  }}
          cargo publish
